spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: org.postgresql.Driver
    username: "postgres"
    password: "root"
  jpa:
    hibernate.ddl-auto: create-drop

secret:
  jwt:
    secret-key: verysecretkey